### ISSUE TITLE
Live2dCubismCore.h

### ISSUE THREAD

**Issue by sibo7851** [renpy/renpy-build#11]
So after realizing that the tars file was completely empty and there was zero mention of it in the build readme, and after getting the tar files to proceed with compiling I stumbled into this lovely issue where the compiler realizes that Live2dCubismCore.h is not accessible.  After pondering to myself why someone would just leave this out I also realized that it uses an older version of the Cubism SDK.  Seems like a couple of fairly important things to mention, but what do I know?

**Comment by renpytom** [comment]
Clearly, not how to participate on github. Please check out the community guidelines:

https://docs.github.com/en/free-pro-team@latest/github/site-policy/github-community-guidelines

**Comment by sibo7851** [comment]
Sorry if I came across as a little annoyed that I spent an hour compiling just to run into this issue.  I'd hardly say your sarcastic answer makes you the bigger person however.  I just assumed I wouldn't get any help with this issue, you can continue to prove me right I guess.

**Comment by sibo7851** [comment]
The solution by the way was to download the Cubism SDK, extract it, go to Core/include/ and copy Live2dCubismCore.h to renpy-build/tmp/install.linux-x86_64/include/

You're welcome github community, because I actually care.

**Comment by VXsz** [comment]
> The solution by the way was to download the Cubism SDK, extract it, go to Core/include/ and copy Live2dCubismCore.h to renpy-build/tmp/install.linux-x86_64/include/
> 
> You're welcome github community, because I actually care.

Love you, sibo7851.
