### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by Delwddrylliwr** [renpy/renpy-build#13]
I noticed in the Issues for the original rapt project that python 3 support is/was planned imminently for renpy-build. But, I'm struggling to find any more information on the status of this. Python 3 for porting pygame to Android (and elsewhere) will be invaluable, thanks so much for your work so far!

Has python 3 support been introduced?

**Comment by renpytom** [comment]
Python 3 support is (finally) in the nightlies.
