### ISSUE TITLE
Renpy 8.2.1 compiles for minsdk 33 but google play requires minsdk 34

### ISSUE THREAD

**Issue by RubenGarcia** [renpy/renpy-build#137]
Can you update it and add a link in the Readme to the current version?
I did not see in the renpy UI a way to change this, could this be added?
Is there a different way to change this in config files?

**Comment by renpytom** [comment]
Coming in 8.3.

**Comment by RubenGarcia** [comment]
If I have time, I will find the place in the code where minsdk is decided and add a PR mentioning it in the readme.
