### ISSUE TITLE
Windows Visual Studio compilation

### ISSUE THREAD

**Issue by balancedwolf** [renpy/renpy-build#22]
Talking about porting to other devices, we have confirmed with a game that pygame runs fine on Android using the kivy framework, but that still requires Python 3, the thing is that we made pygame run on Xbox One and we use Visual Studio for all this related. 

Our concern is to port to UWP, like Microsoft Store Apps and specifically targeting Xbox One/Series X, question arises here:

Is there anything like a Windows-Only build environment? Like pre-cythonized c files that can be dropped to Visual Studio, or any .sln solution file that already handles building? How does building under Windows work?

**Comment by renpytom** [comment]
No.
