### ISSUE TITLE
Dependencies python-dev-is-python2 and libjpeg-turbo8-dev

### ISSUE THREAD

**Issue by asda488** [renpy/renpy-build#26]
The library `python-dev-is-python2` seems to not be needed, and the libary `libjpeg-turbo8-dev` seems to have been replaced with `libjpeg-dev` on my machine, so I was wondering if these needed changed or whether it was just local.

**Comment by samoyemen** [comment]
Good

**Comment by renpytom** [comment]
This is probably obsolete at this point, now that we mostly run on Python 3 and with libjpeg.
