### ISSUE TITLE
SDL 2.0.16 brings optimization to SDL_WaitEvent

### ISSUE THREAD

**Issue by mwcampbell** [renpy/renpy-build#43]
SDL version 2.0.16 includes [this commit](https://github.com/libsdl-org/SDL/commit/0dd7024d55019182b9e92d65221824a7a4dac992) which enables `SDL_WaitEvent` to actually wait for an OS event instead of polling. In addition to potentially being more power-efficient, this improvement will help with my plan to implement screen reader accessibility for Ren'Py (not quite the same as self-voicing), particularly on Windows, Mac, and iOS.  The problem is that on these platforms, the accessibility API requires IPC to the thread that owns the native window, which has to go through the OS event pumping mechanism, and a single screen reader command can require several IPC round trips, so a 1ms+ delay per round trip (which is what `SDL_WaitEvent` previously did) is noticeable. But at the same time, polling with no delay is obviously a non-starter. So updating to a version of SDL that includes this optimization would be helpful.

**Comment by mwcampbell** [comment]
I decided to move discussion of screen reader accessibility to a new issue: renpy/renpy#3306

**Comment by renpytom** [comment]
We've upgraded SDL2.
