### ISSUE TITLE
PWA: additional caching options

### ISSUE THREAD

**Issue by Vadim-Karpenko** [renpy/renpy-build#53]
I'm creating this issue to discuss further steps for #51 and [https://github.com/renpy/renpy/pull/4126](https://github.com/renpy/renpy/pull/4126). 
Here are a few things we can implement, feel free to suggest more:

- [ ] Cache the entire game for offline use
- [ ] Cache all media we receive (not only core files) as the user progress through the story.
- [ ] If 2nd is active, we should give the ability to purge the cache. I think core files should be kept regardless.
- [ ] Manually select what to precache. 
We can divide all media based on their folders, many devs divide their media content into something like `chapter1/example.png`, or `chapter2/example2.png` and we can use it so the user can decide what content he'd like to save. For example, download only `chapter2` content.
- [ ] Give devs control over cache mode - core files or all media.

To implement all this, we probably need to generate a file that will include all project paths for media content during the build, because I don't think that we can access all of them from the frontend side. Maybe there's a way to get it from web assembly directly? @renpytom

**Comment by renpytom** [comment]
My first inclination is that 'Cache the entire game for offline use' is the right choice. For the other platforms, installing the game means installing all of the media files associated with the game. It think it makes sense to continue that when a PWA is involved - installing the game means installing all the files needed to run the game offline.

**Comment by Vadim-Karpenko** [comment]
> My first inclination is that 'Cache the entire game for offline use' is the right choice. For the other platforms, installing the game means installing all of the media files associated with the game. It think it makes sense to continue that when a PWA is involved - installing the game means installing all the files needed to run the game offline.

Makes sense, but it may cause a significant increase in bandwidth to the server if the amount of users is big, and not everyone will use CDNs to fix it. Maybe we should create an option in the config to let the dev decide? And I think would be nice to give some sort of prompt to ask the user if he'd like to install everything or just core files and download everything else progressively.

**Comment by renpytom** [comment]
I believe this has been satisified.
