### ISSUE TITLE
Windows: Add ARM64 native support

### ISSUE THREAD

**Issue by qinlili23333** [renpy/renpy-build#55]
Currently there is no arm64 native support for RenPy, this means on arm devices such as Surface Pro X, game run in x86 simulator mode, which is low effeciency.
It's time to add arm64 native support as Python3 has already support arm64.

**Comment by renpytom** [comment]
Do you have any statistics as to how popular ARM64 on Windows is? The Steam hardware survey shows 0.03%, so it may not be worth it.

**Comment by qinlili23333** [comment]
> Do you have any statistics as to how popular ARM64 on Windows is? The Steam hardware survey shows 0.03%, so it may not be worth it.


Actually arm64 users are more than Steam shows, the poor compatibility stops most arm64 users try to install games.
Currently, Microsoft has decided to continuously release arm Surface, so as Huawei and Samsung, mostly use Qualcomm chips. And another large user group is users who use Windows arm virtual machines on arm based Mac devices like M1 chips.
So as arm user group is growing, although currently it's really a small group comparing to x86 users (but more than Linux arm users), but as a large open-source game engine, I think we should consider to support arm natively. Unity and Unreal have already anounced to support arm64 natively.
This don't need to complete in a short time, but at least, it's time to put it on the plan.

**Comment by renpytom** [comment]
I'm closing this for now, as I don't see this as a goal for the moment. (I'll re-evaluate if windows-on-arm gains popularity.)

**Comment by hadeutscher** [comment]
I think WoA has gained some popularity lately :) maybe you could re-evaluate this?
